In [1]:
import numpy as np
import torch

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [2]:
# let us run this cell only in CUDA is available

In [3]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

NameError: name 'x' is not defined

In [4]:
x = torch.randn(1)

In [5]:
print(x)

tensor([2.2363])


In [6]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([3.2363], device='cuda:0')
tensor([3.2363], dtype=torch.float64)


In [7]:
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib'

In [8]:
x = torch.ones(2, 2, requires_grad=True)

In [9]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [10]:
y = x + 2

In [11]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [12]:
print(y.grad_fn)

In [13]:
z = y * y * 3

In [14]:
out = z.mean()

In [15]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [16]:
a = torch.randn(2, 2)

In [17]:
a = ((a * 3) / (a - 1))

In [18]:
print(a.requires_grad)

False


In [19]:
a.requires_grad_(True)

tensor([[-4.1907,  0.5512],
        [ 0.3804,  1.3975]], requires_grad=True)

In [20]:
b = (a * a).sum()

In [21]:
print(b.grad_fn)

In [22]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [23]:
out.backward()

In [24]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [25]:
print(y.grad)

None
